#!/bin/bash
for i in */ ;
do
	echo -n "$i : "
	points=0;
	for j in subsums;
	do
		g++ $i/$j.cpp -o $j.exe -O2 -s -static -lm -x c++ ;

		for k in `seq -w 1 20` ; 
		do
			timeout 2s ./$j.exe < ../$j/tests/$j.$k.in > output;
			signal=$?;
			if [[ $signal -eq 0 ]] ;
			then
				if [[ "`diff -w output ../$j/tests/$j.$k.sol`" = "" ]] ; 
				then 
					echo -n "+5 " ; 
					points=$(($points+5));
				else
					echo -n "+0 " ;
				fi ; 
			else
				if [[ $signal -eq 124 ]] ;
				then
					echo -n "TL ";
				else
					if [[ 1 -eq 1 ]] ;
					then
						echo -n "NF ";
					else
						echo -n "RE ";
					fi
				fi
			fi
			rm output;
		done
		rm $j.exe;
	done

	for j in color;
	do
		g++ $i/$j.cpp -o $j.exe -O2 -s -static -lm -x c++ ;

		for k in `seq -w 1 20` ; 
		do
			timeout 0.6s ./$j.exe < ../$j/tests/$j.$k.in > output;
			signal=$?;
			if [[ $signal -eq 0 ]] ;
			then
				if [[ "`diff -w output ../$j/tests/$j.$k.sol`" = "" ]] ; 
				then 
					echo -n "+5 " ; 
					points=$(($points+5));
				else
					echo -n "+0 " ;
				fi ; 
			else
				if [[ $signal -eq 124 ]] ;
				then
					echo -n "TL ";
				else
					if [[ 1 -eq 1 ]] ;
					then
						echo -n "NF ";
					else
						echo -n "RE ";
					fi
				fi
			fi
			rm output;
		done

		rm $j.exe;
	done

	for j in traffic;
	do
		g++ $i/$j.cpp -o $j.exe -O2 -s -static -lm -x c++ ;

		for k in `seq -w 1 50` ; 
		do
			timeout 0.2s ./$j.exe < ../$j/tests/$j.$k.in > output;
			signal=$?;
			if [[ $signal -eq 0 ]] ;
			then
				if [[ "`diff -w output ../$j/tests/$j.$k.sol`" = "" ]] ; 
				then 
					echo -n "+2 " ; 
					points=$(($points+2));
				else
					echo -n "+0 " ;
				fi ; 
			else
				if [[ $signal -eq 124 ]] ;
				then
					echo -n "TL ";
				else
					if [[ 1 -eq 1 ]] ;
					then
						echo -n "NF ";
					else
						echo -n "RE ";
					fi
				fi
			fi
			rm output;
		done

		rm $j.exe;
	done
	echo $points
done
